# Generated by Django 5.2.13 on 2026-05-04 10:34

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Ismi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('height', models.FloatField(blank=True, null=True, verbose_name="Bo'y (sm)")),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Vazn (kg)')),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('lose', "Vazn yo'qotish"), ('gain', 'Vazn oshirish'), ('maintain', 'Vaznni saqlash'), ('endurance', 'Chidamlilik')], max_length=20)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Past (kam harakat)'), ('light', 'Engil (haftada 1-3)'), ('moderate', "O'rtacha (haftada 3-5)"), ('active', 'Yuqori (har kuni)')], max_length=20)),
                ('daily_calorie_goal', models.PositiveIntegerField(default=2000)),
                ('daily_water_goal', models.PositiveIntegerField(default=2500)),
                ('daily_step_goal', models.PositiveIntegerField(default=8000)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('notif_workout', models.BooleanField(default=True)),
                ('notif_water', models.BooleanField(default=True)),
                ('notif_weekly_report', models.BooleanField(default=True)),
                ('notif_achievements', models.BooleanField(default=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
    ]
