# Generated by Django 5.2.13 on 2026-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('distance_km', models.FloatField(default=0)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('goal', models.PositiveIntegerField(default=8000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qadam',
                'verbose_name_plural': 'Qadamlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WaterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.PositiveIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_ml', models.PositiveIntegerField(default=0)),
                ('goal_ml', models.PositiveIntegerField(default=2500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suv (kunlik)',
                'verbose_name_plural': 'Suv (kunlik)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='weight/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vazn',
                'verbose_name_plural': 'Vazn yozuvlari',
                'ordering': ['-date'],
            },
        ),
    ]
