# Generated by Django 5.2.13 on 2026-05-04 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trackers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='steprecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waterintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trackers.waterintake'),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='steprecord',
            index=models.Index(fields=['user', 'date'], name='trackers_st_user_id_80b215_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='steprecord',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='waterintake',
            index=models.Index(fields=['user', 'date'], name='trackers_wa_user_id_cdaf85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waterintake',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='weightlog',
            index=models.Index(fields=['user', 'date'], name='trackers_we_user_id_b985e2_idx'),
        ),
    ]
