# Generated by Django 5.2.13 on 2026-05-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name_uz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('national', 'Milliy taomlar'), ('fast_food', 'Fast food'), ('fruit', 'Mevalar'), ('vegetable', 'Sabzavotlar'), ('meat', "Go'sht"), ('dairy', 'Sutli mahsulotlar'), ('grain', 'Don mahsulotlari'), ('drink', 'Ichimliklar'), ('other', 'Boshqa')], max_length=20)),
                ('calories', models.FloatField(help_text='100g uchun (kkal)')),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('default_portion', models.PositiveIntegerField(default=100, help_text='gramm')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taom (baza)',
                'verbose_name_plural': 'Taomlar bazasi',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('snack', 'Yengil ovqat')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('portion_size', models.FloatField(help_text='gramm')),
                ('calories', models.FloatField()),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('manual', "Qo'lda"), ('database', 'Bazadan'), ('barcode', 'Barkod')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='meals.fooditem')),
            ],
            options={
                'verbose_name': "Iste'mol qilingan taom",
                'verbose_name_plural': 'Kundalik taomlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
