# Generated by Django 5.2.13 on 2026-05-04 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kun',
                'verbose_name_plural': 'Kunlar',
                'ordering': ['plan', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_uz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='plans/')),
                ('cover_url', models.URLField(blank=True)),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20)),
                ('total_days', models.PositiveSmallIntegerField()),
                ('workouts_per_week', models.PositiveSmallIntegerField(default=3)),
                ('target_goal', models.CharField(choices=[('lose', "Vazn yo'qotish"), ('gain', 'Vazn oshirish'), ('maintain', 'Saqlash'), ('endurance', 'Chidamlilik')], default='maintain', max_length=20)),
                ('estimated_duration', models.PositiveSmallIntegerField(help_text='Bir kunlik mashq daqiqasi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dastur',
                'verbose_name_plural': 'Dasturlar',
                'ordering': ['level', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.PositiveSmallIntegerField(default=10)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutday')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exercises.exercise')),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.workoutplan'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_day_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('mood', models.CharField(blank=True, choices=[('great', "Zo'r"), ('good', 'Yaxshi'), ('okay', "O'rtacha"), ('tired', 'Charchadim')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workouts.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessiya',
                'verbose_name_plural': 'Sessiyalar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.PositiveSmallIntegerField(default=0)),
                ('reps_per_set', models.JSONField(blank=True, default=list)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['session', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('plan', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'started_at'], name='workouts_wo_user_id_d379c3_idx'),
        ),
    ]
