# Generated by Django 5.2.13 on 2026-05-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='fitness', max_length=50)),
                ('color', models.CharField(default='#FF6B35', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name_uz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('muscle_groups', models.CharField(blank=True, help_text="Vergul bilan: 'pectoralis,triceps'", max_length=255)),
                ('equipment', models.CharField(choices=[('none', "Yo'q"), ('dumbbell', 'Gantel'), ('barbell', 'Shtanga'), ('kettlebell', 'Girya'), ('band', 'Rezina'), ('machine', 'Trenajor')], default='none', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20)),
                ('instructions_uz', models.TextField(blank=True, help_text='Har bir qadam yangi qator (\\n)')),
                ('instructions_ru', models.TextField(blank=True)),
                ('instructions_en', models.TextField(blank=True)),
                ('tips_uz', models.TextField(blank=True)),
                ('tips_ru', models.TextField(blank=True)),
                ('tips_en', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exercises/thumbs/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('default_reps', models.PositiveIntegerField(default=10)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('calories_per_minute', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.exercisecategory')),
            ],
            options={
                'verbose_name': 'Mashq',
                'verbose_name_plural': 'Mashqlar',
                'ordering': ['category', 'name_uz'],
                'indexes': [models.Index(fields=['category', 'difficulty'], name='exercises_e_categor_7c6085_idx'), models.Index(fields=['is_active'], name='exercises_e_is_acti_763092_idx')],
            },
        ),
    ]
